#Libraries
#packages
install.packages("Quandl")
library(Quandl)
install.packages("quantmod")
library(quantmod)
install.packages("xts")
library("xts")
install.packages("zoo")
library("zoo")
install.packages("devtools")
library("devtools")
require(devtools)
install_github("braverock/FinancialInstrument")
library("FinancialInstrument")
install_github("joshuaulrich/xts")
library("xts")
install_github("braverock/blotter")
library("blotter")
install_github("braverock/quantstrat")
library("quantstrat")
install_github("braverock/PerformanceAnalytics")
library("PerformanceAnalytics")


